name: Deploy Supabase Migrations

on:
  push:
    branches:
      - main # Adjust if your production branch has a different name

jobs:
  deploy-migrations:
    runs-on: ubuntu-latest
    # Optional: If you use GitHub environments for secrets
    # environment: production
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.PRODUCTION_DB_PASSWORD }}
      PRODUCTION_PROJECT_REF: ${{ secrets.PRODUCTION_PROJECT_REF }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest # Or pin to a specific version like '1.100.0'

      - name: Link Supabase project (Production)
        run: supabase link --project-ref $PRODUCTION_PROJECT_REF
        # The CLI should pick up SUPABASE_DB_PASSWORD from env for non-interactive use

      - name: Apply database migrations (Production)
        run: supabase db push --include-all
        # Using db push as it's often more reliable for remote deployments in CI